VERSION=3.8.1
MQ_PORT=5672
WEB_PORT=15672
HOSTNAME=myRabbit
DEFAULT_VHOST=my_vhost
DEFAULT_USER=admin
DEFAULT_PASS=admin
VOLUMES=$PWD/volumes

docker run -d --name rabbitmq-${VERSION} -p ${MQ_PORT}:5672 -p ${WEB_PORT}:15672 -v ${VOLUMES}:/var/lib/rabbitmq --hostname ${HOSTNAME} -e RABBITMQ_DEFAULT_VHOST=${DEFAULT_VHOST}  -e RABBITMQ_DEFAULT_USER=${DEFAULT_USER} -e RABBITMQ_DEFAULT_PASS=${DEFAULT_PASS} rabbitmq:${VERSION}-management